name = "DPSphericalMeans"
uuid = "48b29ae0-2b76-4703-91b5-599984b6c68b"
authors = ["Atour Mousavi Gourabi"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"

[compat]
BenchmarkTools = "1.6.3"
LinearAlgebra = "1.11.0"
MKL = "0.9.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
